// frameworks/vue/src/app/Counter.vue
<template>
  <div>
    <button class="btn btn-primary btn-block" id="counter-btn" @click="increment">
      Count: {{ count }}
    </button>
    <p class="list-item">Update delay: {{ updateTime }} ms</p>
  </div>
</template>

<script>
import {ref, onUnmounted} from 'vue';

export default {
  setup() {
    const count = ref(0);
    let updateTime = ref(0);

    let countUpdateTime = 0
    // 每秒自动递增
    const interval = setInterval(() => {
      if (count.value === 1000) {
        clearInterval(interval);
        return;
      }
      const startTime = performance.now();
      count.value++;
      const endTime = performance.now();
      countUpdateTime += endTime - startTime;
      updateTime.value = countUpdateTime;
    }, 10);

    const  increment = () => {
      count.value++;
    };
    // 清理间隔
    onUnmounted(() => clearInterval(interval));

    return { count, updateTime, increment };
  }
};
</script>

// frameworks/solidjs/src/app/Counter.tsx
import {createSignal, onCleanup} from "solid-js";

export const Counter = () => {
  const [count, setCount] = createSignal(0);
  const [updateTime, setUpdateTime] = createSignal(0);

  let countUpdateTime = 0;
  // 每秒自动递增
  const interval = setInterval(() => {
    if (count() === 1000) {
      clearInterval(interval);
      return;
    }
    const startTime = performance.now();
    setCount(c => c + 1);
    const endTime = performance.now();
    countUpdateTime += endTime - startTime;
    setUpdateTime(countUpdateTime);
  }, 10);

  // 清理间隔
  onCleanup(() => clearInterval(interval));

  return (
    <div>
      <button className={"btn btn-primary btn-lg"} id="counter-btn" onClick={() => setCount(count() + 1)}>
        Count: {count()}
      </button>
      <p className={'list-item'}>Update delay: {updateTime()} ms</p>
    </div>
  );
}
