// packages/vue/src/app/Counter.vue
<template>
  <div>
    <button id="counter-btn" @click="increment">
      Count: {{ count }}
    </button>
    <p>Update delay: {{ updateTime }} ms</p>
  </div>
</template>

<script>
import {ref, onUnmounted} from 'vue';

export default {
  setup() {
    const count = ref(0);
    let updateTime = ref(0);

    let countUpdateTime = 0
    // 每秒自动递增
    const interval = setInterval(() => {
      if (count.value === 1000) {
        clearInterval(interval);
        return;
      }
      const startTime = performance.now();
      count.value++;
      const endTime = performance.now();
      countUpdateTime += endTime - startTime;
      updateTime.value = countUpdateTime;
    }, 10);

    const  increment = () => {
      count.value++;
    };
    // 清理间隔
    onUnmounted(() => clearInterval(interval));

    return { count, updateTime, increment };
  }
};
</script>

// frameworks/svelte/src/app/Counter.svelte
<script>
    let count = 0;
    let updateTime = 0;

    // 每秒自动递增
    $: interval = setInterval(() => {
        if (count === 1000) {
            clearInterval(interval);
            return;
        }
        count++;
        const startTime = performance.now();
        count++;
        const endTime = performance.now();
        updateTime += endTime - startTime;
    }, 10);

    // 清理间隔
    function destroy() {
        clearInterval(interval);
    }
</script>

<button id="counter-btn" on:click={() => count++}>
    Count: {count}
</button>
<p>Update delay: {updateTime} ms</p>

<style>
    button {
        font-size: 1.2em;
        padding: 10px;
    }
</style>
