// packages/solidjs/src/app/VirtualList.tsx
import { createSignal, createMemo, onMount } from 'solid-js';

export function VirtualList() {
  // 基础配置
  const itemHeight = 50; // 每个列表项高度
  const visibleCount = 10; // 可视区域显示 10 行
  const viewHeight = itemHeight * visibleCount; // 可视区域高度
  const totalItems = 10000; // 总数据量
  // 总高度计算（用于占位）
  const totalHeight = createMemo(() => totalItems * itemHeight);

  // const [data] = createSignal(new Array(10000).fill(null).map((_, index) => ({ index: index + 1 })));
  const [scrollTop, setScrollTop] = createSignal(0);
  const [start, setStart] = createSignal(0);
  const [end, setEnd] = createSignal(visibleCount);

  // 计算可视区域项
  const visibleItems = createMemo(() => {
    const startIndex = start();
    const endIndex = Math.min(end(), totalItems);
    const indices = [];
    for (let i = startIndex; i < endIndex; i++) {
      indices.push(i);
    }
    return indices;
  });

  // 滚动事件处理
  function handleScroll(event) {
    const container = event.target;
    setScrollTop(container.scrollTop);
    setStart(Math.floor(scrollTop() / itemHeight));
    setEnd(start() + visibleCount);
  }

  return (
    <div class='virtual-container' onScroll={handleScroll}>
      {/* 虚拟总高度 */}
      <div style={{ height: `${totalHeight()}px` }}>
        {/* 可视区域内容 */}
        <div
          style={{
            transform: `translateY(${start() * itemHeight}px)`,
            position: 'absolute',
            top: '0',
            left: '0',
            width: '100%'
          }}
        >
          {visibleItems().map(item => (
            <div class={'list-item'} key={item}>
              <p>Item {item + 1}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// frameworks/svelte/src/app/VirtualList.svelte
<script>
    import { state } from 'svelte';

    const data = Array(10000).fill(null).map((_, index) => ({ index }));

    let scrollTop = state(0);
    let start = state(0);
    let end = state(20);

    // 计算可见区域的开始和结束索引
    $: {
        const itemHeight = 50;
        const viewStart = Math.floor(scrollTop / itemHeight);
        const viewEnd = viewStart + 20; // 假设可视区域显示 20 条

        start = viewStart;
        end = Math.min(viewEnd, data.length); // 防止超出范围
    }

    // 占位高度
    // $: placeholderHeight = data.length * 50;

    // 滚动事件处理
    function handleScroll(event) {
        const container = event.target;
        const clientHeight = container.clientHeight;
        const scrollHeight = container.scrollHeight;
        const itemHeight = 50;

        // 计算可见区域的开始和结束索引
        const viewStart = Math.floor(scrollTop.value / itemHeight);
        const viewEnd = viewStart + Math.ceil(clientHeight / itemHeight);

        setStart(viewStart);
        setEnd(viewEnd);
    }

    // 设置占位高度
    // $: placeholderHeight = data.length * 50;
</script>

<div class="scroll-container" on:scroll={handleScroll}>
    <!-- 占位元素 -->
    <div style="height: {placeholderHeight}px"></div>

    <!-- 可视区域 -->
    <div style="transform: translateY(-{start * 50}px)">
        {#each data.slice(start, end) as item}
            <div class="list-item" key={item.index}>
                <p>Item {item.index}</p>
            </div>
        {/each}
    </div>
</div>

<style>
    scroll-container {
        position: relative;
        height: 400px;
        width: 300px;
        overflow-y: auto;
        border: 1px solid #ccc;
    }

    list-item {
        height: 50px;
        padding: 10px;
    }
</style>
